# Generated by Django 5.2.7 on 2025-10-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'ยังไม่ชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('processing', 'กำลังเตรียมสินค้า'), ('shipped', 'กำลังจัดส่ง'), ('delivered', 'จัดส่งสำเร็จ'), ('cancelled', 'ยกเลิก')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
